MIN_BEST_RIDGELINE = 5
DEFAULT_X_LABEL = 'Time'
DEFAULT_Y_LABEL = 'Value'
PORTFOLIO_URL = 'https://towardsdatascience.com/author/piero-paialunga/'
MIN_X = 0.01
MAX_X = 50.
X_STEP = 0.1
MIN_POINTS = 10
MAX_POINTS = 10_000
POINTS_STEP = 10
MIN_NOISE = 0.
MAX_NOISE = 100.
STEP_NOISE = 0.1
SPECTOGRAM_WINDOW_SIZE = 256
SPECTOGRAM_OVERLAP = 128
SPECTOGRAM_CMAP = 'inferno'
STATISTICS_DF_COLUMNS = ["Min", "Max", "Mean", "Median", "25% Quartile", "50% Quartile (Median)", "75% Quartile"]
QUARTILES = [25, 50, 75]
DEFAULT_TS = "5*x + 5*log(x) + 10*sin(x)"
DEFAULT_STATISTICS_NAME = "descriptive_statistics.csv"